services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: radio-demon-warehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"  

  rabbitmq:
    image: rabbitmq:3-management
    expose:
      - "5672"
      - "15672"

  gilgamesh:
    build:
      context: ./gilgamesh
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./gilgamesh:/app
    working_dir: /app
    command: npm run start:prod
    expose:
      - "3000" 

  kayn:
    build:
      context: ./kayn
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./kayn:/app
    working_dir: /app
    command: npm run start:prod
    expose:
      - "3001"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - gilgamesh
      - kayn

volumes:
  pgdata:
